CoursesStore/Models/BasketItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CoursesStore.Models
{
    public class BasketItem
    {
        public Course Course { get; set; }
        public int Count { get; set; }
        public decimal Value { get; set; }
       

        public decimal TotalPrice { get { return Count * Value; }  }
    }
}

CoursesStore/ViewModels/BasketViewModel.cs
using CoursesStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CoursesStore.ViewModels
{
    public class BasketViewModel
    {
        public List<BasketItem> BasketItem { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

CoursesStore/Controllers/BasketController.cs
using CoursesStore.Infrastructure;
using CoursesStore.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesStore.Controllers
{
    public class BasketController : Controller
    {

        private BasketManager BM;

        public BasketController()
        {
            BM = new BasketManager(new SessionManager(), new DAL.CoursesContext());
        }

        public object BasektViewMode { get; private set; }

        // GET: Basket
        public ActionResult Index()
        {
            var basketItems = BM.GetBasket();

            BasketViewModel basketVM = new BasketViewModel()
            {
                BasketItem = basketItems,
                TotalPrice = BM.SumBasketPrice
            };

            return View(basketVM);
        }



        public ActionResult RemoveRecrod(int courseId)
        {
            var removeItemBasket = BM.RemoveItem(courseId);

            return UpdateBasketUI();
        }

        public ActionResult UpdateRecord(int courseId, int quantity)
        {
            BM.UpdateQuantity(courseId, quantity);

            return UpdateBasketUI();
        }

        private ActionResult UpdateBasketUI()
        {
            var countBasketItemBasket = BM.CountBasketItem();
            var sumBasketPriceBasket = BM.SumBasketPrice;
            var sumBasketPriceAfterDiscountBasket = BM.SumBasketPriceAfterDiscount;

            var basketItems = BM.GetBasket();
            string viewContent = ConvertViewToString("_BasketItems", basketItems);

            return Json(new { itemsHTML = viewContent, CountBasketItem = countBasketItemBasket, NetBasketPrice = sumBasketPriceAfterDiscountBasket, SumBasketPrice = sumBasketPriceBasket });

        }

        private string ConvertViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (StringWriter writer = new StringWriter())
            {
                ViewEngineResult vResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext vContext = new ViewContext(this.ControllerContext, vResult.View, ViewData, new TempDataDictionary(), writer);
                vResult.View.Render(vContext, writer);
                return writer.ToString();
            }
        }

        public decimal GetPriceBasket()
        {
            decimal Total = BM.SumBasketPrice;
            return Total;
        }

        public decimal GetNetPriceBasket()
        {
            decimal Total = BM.SumBasketPriceAfterDiscount;
            return Total;
        }

        public int CountBasket()
        {
            int Counter = BM.CountBasketItem();
            return Counter;
        }

    }
}

CoursesStore/Views/Basket/Index.cshtml
@model CoursesStore.ViewModels.BasketViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="cart-main-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="s-title">
                    <h1>Twój koszyk</h1>
                </div>
                <form action="#">
                    <div class="cart-table table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th class="p-times">Usuń</th>
                                    <th class="p-image">Obrazek</th>
                                    <th class="p-name">Nazwa kursu</th>
                                    <th class="p-amount">Cena</th>
                                    <th class="p-discount">Rabat</th>
                                    <th class="p-quantity">Antal</th>
                                    <th class="p-total">Suma</th>
                                </tr>
                            </thead>
                            <tbody class="basket-items">
                                @{Html.RenderPartial("_BasketItems", Model.BasketItem);}

                            </tbody>
                        </table>
                        <div class="all-cart-buttons">
                            <a href="">Kontynuuj zakupy</a>
                            <div class="float-right">
                                <a href="#">Wyczyść koszyk </a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="shipping-discount">
                                <p>Potiwerdz dane zamawiajaćego</p>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-6">
                                        <div class="level">
                                            Płatnik: <span class="required" title="required"></span>
                                        </div>
                                        <div class=" shipping-wrapper">
                                            <select class="country">
                                                <option value="state">Osoba prywatna</option>
                                                <option value="state">Firma</option>

                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="postal-code">
                                            <div class="level">
                                                Imię i nazwisko:
                                            </div>
                                            <input type="text" placeholder="">
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="postal-code">
                                            <div class="level">
                                                Ulica:
                                            </div>
                                            <input type="text" placeholder="">
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="postal-code">
                                            <div class="level">
                                                Miejscowość:
                                            </div>
                                            <input type="text" placeholder="">
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="postal-code">
                                            <div class="level">
                                                Kod pocztowy:
                                            </div>
                                            <input type="text" placeholder="">
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="shipping-discount">

                                <p>Wypełnij poniższe dane w przyadku gdy zamawiasz na firme</p>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="postal-code">
                                            <div class="level">
                                                Nazwa firmy:
                                            </div>
                                            <input type="text" placeholder="">
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="postal-code">
                                            <div class="level">
                                                NIP:
                                            </div>
                                            <input type="text" placeholder="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="shipping-discount">
                                <div class="shipping-title">
                                    <h3>Kod rabaotowy</h3>
                                </div>
                                <p>Jeżeli posiadasz kod rabatowy wpisz go tutaj</p>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="postal-code">
                                            <input type="text" placeholder="">
                                        </div>
                                        <input type="submit" value="Wykorzystaj kod" name="#" class="button second">
                                    </div>
                                </div>
                            </div>
                            <div class="amount-totals">
                                <p class="total">Kwota netto: <span><span id="net-total">@Html.Action("GetNetPriceBasket", "Basket")</span> zł</span></p>
                                <p class="total">Kwota brutto: <span><span id="gross-total">@Html.Action("GetPriceBasket", "Basket")</span> zł</span></p>

                                @if (Model.TotalPrice > 0)
                                {
                                    <input type="submit" value="Opłać zamówienie" name="#" class="button">
                                }
                                else
                                {
                                    <div>Twój koszyk jest pusty</div>
                                }
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryAndJqueryUI")
    <script type="text/javascript">

        $(function () {
            bindItemsEvents();
        });

        var removeItem = function () {
            var removeRecord = $(this).closest('tr').attr("data-id");
            if (removeRecord != '') {
                $.post("/Basket/RemoveRecrod", { "courseId": removeRecord },
                    function (response) {
                        updateBasketUI(response);
                        bindItemsEvents();
                    });
                return false;
            }
        };

        var updateQuantity = function () {
            var quantity = $(this).val();
            var updateRecord = $(this).closest('tr').attr("data-id");
            if (updateRecord != '') {
                $.post("/Basket/UpdateRecord", { "courseId": updateRecord, "quantity": quantity },
                    function (response) {
                        updateBasketUI(response);
                        bindItemsEvents();
                    });
            }
        };


        var limitInput = function () {
            var value = parseInt(this.value, 10);
            var max = parseInt(this.max, 10);
            var min = parseInt(this.min, 10);

            if (value > max) {
                this.value = max;
            } else if (value < min) {
                this.value = min
            }
        };


        function updateBasketUI(response) {
            $('.basket-items').html(response.itemsHTML);

            $('#BucketPrice').text(parseFloat(response.SumBasketPrice).toFixed(2));
            $('#BucketCount').text(response.CountBasketItem);

            $('#net-total').text(parseFloat(response.NetBasketPrice).toFixed(2));
            $('#gross-total').text(parseFloat(response.SumBasketPrice).toFixed(2));
        }

        function bindItemsEvents() {
            $(".p-action").click(removeItem);
            $(".quantity").change(limitInput);
            $(".quantity").change(updateQuantity);
        }



    </script>
}

CoursesStore/Views/Basket/_BasketItems.cshtml
@model List<CoursesStore.Models.BasketItem>

@foreach (var item in Model)
{
    <tr data-id="@item.Course.CourseId" >
        <td class="p-action" ><a href="#"><i class="fa fa-times"></i></a></td>
        <td class="p-image">
            <a href="@Url.Action("Details", "Courses", new { coursesId = item.Course.CourseId } )"><img src="@Url.Content("~/Content/img/product/" + item.Course.ImageFileName)"></a>
        </td>
        <td class="p-name"><a href="@Url.Action("Details", "Courses", new { coursesId = item.Course.CourseId } )">@item.Course.CourseTitle</a></td>
        <td class="p-amount"><span  class="amount">@item.Course.CoursePrice</span> zł</td>
        <td class="p-amount"><span class="amount">@item.Course.DiscountPercentage</span> %</td>
        <td class="p-quantity" ><input class="quantity" type="number" min="1" max="99"  value="@item.Count" /></td>
        <td class="p-total"><span  class="item-totalPrice">@item.TotalPrice</span> zł</td>
    </tr>
}